In [5]:
import numpy as np

def distEuclin(muestra, dataset):
    distancias = np.zeros((dataset.shape[0],1))
    for counter in range(0, dataset.shape[0]):
        distancias[counter] = np.linalg.norm(muestra - dataset[counter])
    return distancias

In [7]:
# Prueba de dsitancias
muestra = np.array([1,2,3,4])
dataset = np.array([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
])
distancias = distEuclin(muestra, dataset)
print(distancias)

[[0.]
 [2.]
 [4.]]

In [9]:
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [15]:
boston_dataset = load_boston()
bostonDataFrame = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
bostonDataFrame['MEDV'] = boston_dataset.target
bostonDataFrame.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [49]:
X = bostonDataFrame[['LSTAT', 'RM']]
Y = bostonDataFrame['MEDV']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.65, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(177, 2)
(329, 2)
(177,)
(329,)

In [50]:
lin_model = LinearRegression()
lin_model.fit(X_train, Y_train)

y_train_predict = lin_model.predict(X_train)
MSE = mean_squared_error(Y_train, y_train_predict)
print("Entrenamiento: MSE = " + str(MSE))

y_test_predict = lin_model.predict(X_test)
MSE = mean_squared_error(Y_test, y_test_predict)
print("Pruebas: MSE = " + str(MSE))

Entrenamiento: MSE = 33.19077733776584
Pruebas: MSE = 29.7073086891134

In [51]:
df_predicciones = pd.DataFrame({'valor_real':Y_test, 'prediccion':y_test_predict})
df_predicciones = df_predicciones.reset_index(drop=True)
df_predicciones.head(10)

   valor_real  prediccion
0        37.6   37.546065
1        27.9   29.558765
2        22.6   26.032313
3        13.8    2.930409
4        35.2   33.735262
5        10.4    9.789465
6        23.9   30.724925
7        29.0   28.031871
8        22.8   26.712986
9        23.2   22.807768